### ISSUE TITLE
Document that cloudinit might fail if you bring your own Docker image

### ISSUE THREAD

**Issue by bschaatsbergen** [bschaatsbergen/terraform-gce-atlantis#76]
Cloudinit performs a chown with the uid 100 (atlantis user) on the GCE Persistent Disk mount path - we should document this so that users are aware that when handrolling their own Docker image.

**Comment by bschaatsbergen** [comment]
This needs to be tested.

**Comment by nitrocode** [comment]
Exposing the script would be a good escape hatch for people using non standard docker images

**Comment by bschaatsbergen** [comment]
This is addressed by @d-costa in #131

**Comment by dimisjim** [comment]
using the latest version of the code from the main branch (as I need the shared-vpc feature), not overriding any default image or atlantis user, but still getting `atlantis-chown-disk.service: Failed with result 'exit-code'.` and very similar to the one mentioned in: https://github.com/bschaatsbergen/terraform-gce-atlantis/issues/107  + `konlet-startup.service: Failed with result 'exit-code'.` Anyone has an idea of what be going wrong?
